// Parameter schema (drives the UI and the shader uniforms) and the design presets.
export const GROUPS = [
  ["time", "Time & view"], ["heat", "Heat"], ["style", "Drawing technique"], ["cut", "Section cut"], ["colour", "Colour"],
  ["overlay", "Labels & layers"], ["sheet", "Sheet"],
];

// type: r = range, c = colour, s = select, b = toggle
export const PARAMS = [
  // --- time & view
  { k: "view", g: "time", t: "s", o: [["obl", "Oblique section"], ["sec", "Plain section"]], v: "obl", l: "View" },
  { k: "day", g: "time", t: "s", o: [["sep22", "22 Sep 2026 (survey day)"], ["jul08", "8 Jul 2026 (38 °C heatwave)"]], v: "sep22", l: "Day" },
  { k: "hour", g: "time", t: "r", min: 0, max: 36, step: 0.0833, v: 17.667, l: "Time", fmt: "time" },
  { k: "lightFollows", g: "time", t: "b", v: true, l: "Light follows the time" },
  { k: "amb", g: "time", t: "r", min: 0, max: 1, step: 0.01, v: 0.55, l: "Night ambient light" },
  { k: "depthFade", g: "time", t: "r", min: 0, max: 1, step: 0.01, v: 0.6, l: "Aerial perspective" },
  // --- heat
  { k: "hInk", g: "heat", t: "r", min: 0, max: 1, step: 0.01, v: 0.85, l: "Stroke colour = temperature" },
  { k: "hWash", g: "heat", t: "r", min: 0, max: 0.6, step: 0.01, v: 0.1, l: "Heat wash" },
  { k: "hIso", g: "heat", t: "r", min: 0, max: 1, step: 0.01, v: 0, l: "Isotherms" },
  { k: "hIsoStep", g: "heat", t: "r", min: 0.5, max: 5, step: 0.5, v: 2, l: "Isotherm step, °C" },
  { k: "hDots", g: "heat", t: "r", min: 0, max: 1, step: 0.01, v: 0, l: "Heat stipple" },
  { k: "hHalo", g: "heat", t: "r", min: 0, max: 3, step: 0.05, v: 0, l: "Radiation rings" },
  { k: "hCut", g: "heat", t: "r", min: 0, max: 1, step: 0.01, v: 0.8, l: "Section cut = temperature" },
  { k: "hPost", g: "heat", t: "r", min: 0, max: 12, step: 1, v: 0, l: "Heat bands (0 = smooth)" },
  { k: "toneHeat", g: "heat", t: "r", min: 0, max: 1, step: 0.01, v: 0, l: "Stroke density = heat (not shade)" },
  { k: "hRel", g: "heat", t: "s", o: [["0", "Absolute °C"], ["1", "Relative to the air"]], v: "1", l: "Scale" },
  { k: "hTmin", g: "heat", t: "r", min: -20, max: 40, step: 0.5, v: -12, l: "Cold end, °C" },
  { k: "hTmax", g: "heat", t: "r", min: 0, max: 70, step: 0.5, v: 12, l: "Hot end, °C" },
  // --- style
  { k: "style", g: "style", t: "s", o: [["0", "Hatching"], ["1", "Stipple"], ["2", "Halftone"], ["3", "Flat fill"], ["4", "Lines only"], ["5", "Engraving"], ["6", "Cells"], ["7", "Ridges (heat lifts the lines)"], ["8", "Pencil grid"], ["9", "Weave"], ["10", "Photoreal (the model as found)"]], v: "0", l: "Technique" },
  { k: "spacing", g: "style", t: "r", min: 0.4, max: 3, step: 0.01, v: 1, l: "Stroke spacing" },
  { k: "width", g: "style", t: "r", min: 0.3, max: 4, step: 0.01, v: 1, l: "Stroke width" },
  { k: "ridge", g: "style", t: "r", min: 0, max: 4, step: 0.01, v: 1, l: "Ridge lift" },
  { k: "wobble", g: "style", t: "r", min: 0, max: 4, step: 0.01, v: 1, l: "Hand tremor" },
  { k: "gaps", g: "style", t: "r", min: 0, max: 0.6, step: 0.01, v: 0.16, l: "Stroke breaks" },
  { k: "jitter", g: "style", t: "r", min: 0, max: 1.5, step: 0.01, v: 1, l: "Angle spread" },
  { k: "toneVar", g: "style", t: "r", min: 0, max: 0.6, step: 0.01, v: 0.16, l: "Tone per stone" },
  { k: "contrast", g: "style", t: "r", min: 0.3, max: 2, step: 0.01, v: 1, l: "Contrast" },
  { k: "t1", g: "style", t: "r", min: 0, max: 1, step: 0.01, v: 0.1, l: "1st layer threshold" },
  { k: "t2", g: "style", t: "r", min: 0, max: 1, step: 0.01, v: 0.42, l: "Cross-hatch threshold" },
  { k: "t3", g: "style", t: "r", min: 0, max: 1.2, step: 0.01, v: 0.68, l: "3rd layer threshold" },
  { k: "seam", g: "style", t: "r", min: 0, max: 4, step: 0.01, v: 1, l: "Joints between stones" },
  { k: "lines", g: "style", t: "r", min: 0, max: 4, step: 0.01, v: 1, l: "Outlines" },
  { k: "vegAmt", g: "style", t: "r", min: 0, max: 1.5, step: 0.01, v: 0.95, l: "Planting" },
  { k: "grain", g: "style", t: "r", min: 0, max: 3, step: 0.01, v: 1, l: "Paper grain" },
  // --- cut
  { k: "cutStyle", g: "cut", t: "s", o: [["0", "Stone by stone"], ["1", "Solid"], ["2", "Stipple"], ["3", "Heat only"], ["4", "Weave (heat threads)"]], v: "0", l: "Poché" },
  { k: "cutDensity", g: "cut", t: "r", min: 0, max: 1.2, step: 0.01, v: 1, l: "Cut density" },
  { k: "cutLine", g: "cut", t: "r", min: 0, max: 3, step: 0.01, v: 1, l: "Cut outline" },
  { k: "earthFade", g: "cut", t: "r", min: 0.4, max: 5, step: 0.05, v: 1.6, l: "Earth fades out, m" },
  // --- colour
  { k: "cPaper", g: "colour", t: "c", v: "#f3eee3", l: "Paper" },
  { k: "cInk", g: "colour", t: "c", v: "#2e2c29", l: "Graphite" },
  { k: "cCut", g: "colour", t: "c", v: "#2a2826", l: "Cut" },
  { k: "cVeg", g: "colour", t: "c", v: "#617d5e", l: "Planting" },
  { k: "cAccent", g: "colour", t: "c", v: "#b8402b", l: "Accent" },
  { k: "r0", g: "colour", t: "c", v: "#3d5f86", l: "Scale: cold" },
  { k: "r1", g: "colour", t: "c", v: "#7d9aa6", l: "Scale: 2" },
  { k: "r2", g: "colour", t: "c", v: "#4a4642", l: "Scale: middle" },
  { k: "r3", g: "colour", t: "c", v: "#b8532a", l: "Scale: 4" },
  { k: "r4", g: "colour", t: "c", v: "#9e1414", l: "Scale: hot" },
  { k: "dark", g: "colour", t: "b", v: false, l: "Dark paper (light inks)" },
  { k: "photoCol", g: "colour", t: "r", min: 0, max: 1, step: 0.01, v: 0, l: "Stone colour from the photos" },
  // --- overlay
  { k: "ovTemps", g: "overlay", t: "b", v: true, l: "Temperatures on the surfaces" },
  { k: "ovPerson", g: "overlay", t: "b", v: true, l: "Person = thermometer" },
  { k: "ovSun", g: "overlay", t: "b", v: true, l: "Sun and heat flows" },
  { k: "ovLegend", g: "overlay", t: "b", v: true, l: "Temperature scale" },
  { k: "ovTitle", g: "overlay", t: "b", v: true, l: "Title and time" },
  { k: "ovNotes", g: "overlay", t: "b", v: true, l: "Notes" },
  { k: "ovScale", g: "overlay", t: "b", v: true, l: "Scale bar and levels" },
  { k: "numbers", g: "overlay", t: "b", v: false, l: "Typographic thermography (numbers)" },
  { k: "numStep", g: "overlay", t: "r", min: 4, max: 30, step: 0.5, v: 9, l: "Numbers: grid step, mm" },
  { k: "numSize", g: "overlay", t: "r", min: 0.3, max: 3, step: 0.05, v: 1, l: "Numbers: size" },
  { k: "story", g: "overlay", t: "b", v: true, l: "Story in 4 steps" },
  { k: "storyX", g: "overlay", t: "r", min: 0, max: 700, step: 1, v: 452, l: "Story: X, mm" },
  { k: "storyY", g: "overlay", t: "r", min: 0, max: 540, step: 1, v: 292, l: "Story: Y, mm" },
  { k: "strip", g: "overlay", t: "b", v: true, l: "Time strip: the same section at 5 moments" },
  { k: "stripX", g: "overlay", t: "r", min: 0, max: 460, step: 1, v: 452, l: "Strip: X, mm" },
  { k: "stripY", g: "overlay", t: "r", min: 0, max: 540, step: 1, v: 410, l: "Strip: Y, mm" },
  { k: "font", g: "overlay", t: "s", o: [["hand", "Handwritten"], ["serif", "Serif"], ["mono", "Mono"], ["grotesk", "Grotesque"]], v: "hand", l: "Typeface" },
  { k: "textScale", g: "overlay", t: "r", min: 0.5, max: 2.5, step: 0.01, v: 1, l: "Text size" },
  { k: "lang", g: "overlay", t: "s", o: [["en", "English"], ["ca", "Català"], ["es", "Español"], ["ru", "Русский"]], v: "en", l: "Sheet language" },
  // --- sheet
  { k: "offX", g: "sheet", t: "r", min: -6, max: 6, step: 0.05, v: 0, l: "Shift drawing X, m" },
  { k: "offZ", g: "sheet", t: "r", min: -4, max: 6, step: 0.05, v: 0, l: "Shift drawing Z, m" },
  { k: "scale", g: "sheet", t: "s", o: [["30", "1:30"], ["40", "1:40"], ["50", "1:50"], ["25", "1:25"], ["20", "1:20"]], v: "30", l: "Scale" },
  { k: "topClip", g: "sheet", t: "r", min: 0, max: 200, step: 1, v: 0, l: "Crop the drawing at the top, mm" },
  { k: "edgeFade", g: "sheet", t: "r", min: 0, max: 60, step: 1, v: 18, l: "Edge dissolve, mm" },
  { k: "focusR", g: "sheet", t: "r", min: 0, max: 30, step: 0.25, v: 10.5, l: "Focus radius, m (0 = all)" },
  { k: "focusX", g: "sheet", t: "r", min: -10, max: 10, step: 0.25, v: -2.5, l: "Focus centre X, m" },
  { k: "focusZ", g: "sheet", t: "r", min: -2, max: 14, step: 0.25, v: 5.5, l: "Focus centre Z, m" },
  { k: "focusSoft", g: "sheet", t: "r", min: 0.5, max: 10, step: 0.25, v: 3.5, l: "Focus softness, m" },
  { k: "split", g: "sheet", t: "b", v: false, l: "Diptych: day | night" },
  { k: "splitX", g: "sheet", t: "r", min: 100, max: 740, step: 1, v: 420, l: "Diptych: divide at X, mm" },
  { k: "splitHour", g: "sheet", t: "r", min: 0, max: 36, step: 0.0833, v: 28, l: "Diptych: right-hand time", fmt: "time" },
  { k: "splitDark", g: "sheet", t: "b", v: true, l: "Diptych: night palette on the right" },
];

export const DEFAULTS = Object.fromEntries(PARAMS.map(p => [p.k, p.v]));

// ----------------------------------------------------------------------------- presets
const NIGHT = { dark: true, cPaper: "#1d1c1a", cInk: "#d8d1c3", cCut: "#cfc6b6", cVeg: "#7f9a78", r2: "#8c8478", r0: "#6f8fb5", r1: "#9fb2bd", r3: "#e0874f", r4: "#ff5a3a" };
const P = (name, note, o) => ({ name, note, o });
export const PRESETS = [
  P("★ Main · banded wall, woven cut", "The working version: the wall and ground beyond in flat bands of heat (after Fisk's meander maps), the cut woven from threads coloured by the heat stored in the mass. Drawing lowered to the middle of the sheet, trimmed at the top.",
    { style: "3", hInk: 1, hPost: 7, hWash: 0.35, lines: 0.7, seam: 1.1, cutStyle: "4", spacing: 0.9, hCut: 0.8, cutLine: 1.8, cCut: "#3b2f2a", cPaper: "#f4efe2",
      r0: "#6d9bb5", r1: "#a9c9a4", r2: "#e9dcae", r3: "#e8a06a", r4: "#c65a5a", cVeg: "#7fa27a", grain: 0.8, font: "serif",
      offZ: 1.6, topClip: 34, stripY: 440, storyY: 330 }),
  P("Thermal ink", "The colour of every stroke is the temperature of that surface: red is hotter than the air, blue is cooler, graphite is the same as the air.", {}),
  P("Graphite & ember", "A graphite drawing; red wash and stipple only where a surface is hotter than the air.",
    { hInk: 0, hWash: 0.16, hDots: 0.8, hCut: 0.6, hTmin: 0, hTmax: 16 }),
  P("Isotherms", "A topography of heat: contour lines every 1 °C over light graphite.",
    { hInk: 0.2, hWash: 0.05, hIso: 0.9, hIsoStep: 1, contrast: 0.7, t2: 0.6, t3: 0.9 }),
  P("Night exhales", "04:00. Dark paper; the stone gives the day's heat back to the air in rings.",
    { hour: 28, ...NIGHT, hHalo: 1.4, hInk: 0.5, hTmin: -2, hTmax: 6, amb: 0.45 }),
  P("Thermal camera", "False colour like an infrared camera, but drawn by hand, cell by cell.",
    { style: "6", hInk: 1, hCut: 1, hWash: 0.45, r0: "#1b0c3f", r1: "#6a1a7a", r2: "#c6364f", r3: "#f28a2e", r4: "#fbe36b",
      cInk: "#1a1a1a", cPaper: "#f2efe8", cVeg: "#3f6f6a", seam: 1.5, hRel: "0", hTmin: 18, hTmax: 46 }),
  P("Cyanotype", "Light lines on Prussian blue, heat in orange.",
    { dark: true, cPaper: "#163456", cInk: "#dfe8ef", cCut: "#e9eef2", cVeg: "#9cc5c0", hInk: 0.55, hCut: 0.5,
      r0: "#9cc5ea", r1: "#cfe0ec", r2: "#e6ecf0", r3: "#ffb36b", r4: "#ff7a3a", style: "4", lines: 1.4, cutStyle: "2", grain: 1.6 }),
  P("Risograph", "Two inks, fluorescent pink and blue; halftone and heavy grain.",
    { cPaper: "#f6f1e6", cInk: "#2c4bb4", cCut: "#2c4bb4", cVeg: "#2c4bb4", hInk: 0.7, r0: "#2c4bb4", r1: "#6b73c9",
      r2: "#8f7fd0", r3: "#f0508a", r4: "#ff3d7f", hWash: 0.25, grain: 2.6, style: "2", spacing: 1.2, cutStyle: "2" }),
  P("Engraving", "Copperplate: the line thickens with shade, one direction per stone.",
    { style: "5", width: 1.6, spacing: 0.8, hInk: 0.6, cInk: "#1f1a17", cPaper: "#efe6d2", wobble: 0.3, gaps: 0.05, jitter: 0.5 }),
  P("Pointillism", "Everything in dots: density is shade, the colour of each dot is temperature.",
    { style: "1", hInk: 1, cutStyle: "2", spacing: 0.9, width: 1.3, hCut: 1 }),
  P("Woodblock", "Flat colours and a bold outline, like a Japanese woodblock print.",
    { style: "3", lines: 2.4, cutLine: 2.5, cutStyle: "1", hInk: 1, hWash: 0.3, cPaper: "#ede3cf", cVeg: "#557a4f",
      r0: "#3b5d7a", r1: "#8aa3a8", r2: "#d7c9a8", r3: "#d9793b", r4: "#b8321e", grain: 1.8, seam: 2.2 }),
  P("Technical drawing", "Strict and architectural: thin lines, a black cut, one red band of heat.",
    { style: "4", lines: 1, cutStyle: "1", cutLine: 1.4, hInk: 0, hCut: 0, hWash: 0.22, hTmin: 2, hTmax: 14,
      font: "grotesk", grain: 0.3, edgeFade: 0, cPaper: "#fbfbf8", vegAmt: 0.6, cVeg: "#8fa38b" }),
  P("Kraft & chalk", "Brown kraft paper, white chalk for light, charcoal for the cut.",
    { dark: true, cPaper: "#8a6a48", cInk: "#f3ead8", cCut: "#2b2118", cVeg: "#cfe0b8", hInk: 0.35, r4: "#ffdf9b", r3: "#ffc275", r2: "#f3ead8",
      r1: "#dfe6e0", r0: "#bfd6e6", grain: 2.4, contrast: 0.8 }),
  P("Newsprint", "Halftone: round dots at 45°, one ink plus red.",
    { style: "2", hInk: 0.8, spacing: 1.1, cPaper: "#f1ede3", grain: 1.4, cutStyle: "1" }),
  P("Watercolour & pen", "Transparent washes of temperature under a thin pen.",
    { style: "4", lines: 1.1, hWash: 0.5, hInk: 0.3, cutStyle: "2", vegAmt: 0.7, grain: 1.6 }),
  P("Only the heat in colour", "Everything grey; only what is hotter than the air is in colour. The most direct answer to 'where is it hot?'.",
    { hInk: 0, hCut: 0, hWash: 0.4, hTmin: 2, hTmax: 14, cInk: "#55524d", cCut: "#3a3835", r0: "#f3eee3", r1: "#f3eee3",
      r2: "#f0c9a8", r3: "#e0764a", r4: "#c21f1f", vegAmt: 0.5, contrast: 0.8 }),
  P("Where to hide", "The opposite logic: what is cooler than the air is highlighted (shade, planting).",
    { hInk: 0.8, hCut: 0.8, hTmin: -6, hTmax: 12, r0: "#1f5fa8", r1: "#6fa3d1", r2: "#b7b2a8", r3: "#9d8f80", r4: "#6c6259" }),
  P("Dusk 20:00", "The sun has set and the stone is still hot: the best moment to see the mass.",
    { hour: 20.25, hHalo: 0.9, hInk: 0.9, amb: 0.5 }),
  P("July afternoon", "8 July 2026, 15:00, air 38 °C: setts and terrace are scorching.",
    { day: "jul08", hour: 15, hRel: "0", hTmin: 22, hTmax: 60 }),
  P("July night", "8 → 9 July, 04:00: the setts stay 5 °C warmer than the air.",
    { day: "jul08", hour: 28, ...NIGHT, hHalo: 1.6, hTmin: -2, hTmax: 7, amb: 0.45 }),
  P("Plain section", "No perspective: just the cut and what lies behind it, fading with depth.",
    { view: "sec", depthFade: 0.85, scale: "30" }),
  P("Tactile cells", "Every stone is a coloured cell taken from the photos, with strokes on top.",
    { style: "6", photoCol: 0.9, hInk: 0.5, hWash: 0, seam: 1.8, cPaper: "#efe9dc", toneVar: 0.3 }),
  P("Minimum", "Only the cut outline, the person and one number. An almost empty sheet.",
    { style: "4", lines: 0.6, cutStyle: "3", hCut: 1, hInk: 0, hWash: 0.2, vegAmt: 0.4, ovNotes: false, grain: 0.5, depthFade: 0.9 }),
  P("Day | Night", "Diptych: 17:40 on the left, the same frame at 04:00 on dark paper on the right. One wall, two states.",
    { split: true, splitX: 420.5, splitHour: 28, story: false, strip: false, hHalo: 1.4, offX: -3.4, offZ: -1.0,
      focusR: 7.5, focusX: -2.0, focusZ: 3.6, focusSoft: 2.5 }),
  P("Numbers", "Typographic thermography: the surfaces are covered by their own temperatures. Size and colour of each figure are the heat.",
    { numbers: true, numStep: 9.5, focusR: 8.5, style: "4", lines: 0.8, hInk: 0.2, hWash: 0.18, cutStyle: "3", hCut: 1, vegAmt: 0.5, ovTemps: false, contrast: 0.6 }),
  P("Only the cut", "A poster: one section in the colour of heat, everything else dissolves into the paper.",
    { focusR: 5.5, focusX: 0.5, focusZ: 3.2, focusSoft: 2.2, depthFade: 1, cutStyle: "0", hCut: 1, hInk: 0.6 }),
  P("Plain section · numbers", "The cut without perspective, covered in its temperatures: the most literal reading.",
    { view: "sec", numbers: true, numStep: 7, style: "4", lines: 0.9, hInk: 0.3, hWash: 0.12, cutStyle: "3", hCut: 1, ovTemps: false, depthFade: 0.9 }),
  // --- inspired (principles, not copies)
  P("Meander bands", "After Harold Fisk's Mississippi meander maps (1944): heat as flat layered bands of colour, like old river courses.",
    { style: "3", hInk: 1, hCut: 1, hPost: 7, hWash: 0.35, lines: 0.7, seam: 0.6, cutStyle: "3", cPaper: "#f4efe2",
      r0: "#6d9bb5", r1: "#a9c9a4", r2: "#e9dcae", r3: "#e8a06a", r4: "#c65a5a", cVeg: "#7fa27a", grain: 0.8, font: "serif" }),
  P("Pulsar", "After the pulsar plot on the cover of Unknown Pleasures (1979): horizontal lines that the heat lifts upward. Heat seen as a tremor.",
    { style: "7", ridge: 1.6, spacing: 1.1, width: 1.2, ...NIGHT, cInk: "#f1ece2", cCut: "#f1ece2", hInk: 0.35, hCut: 0.5, cutStyle: "3",
      vegAmt: 0.6, lines: 0, grain: 0.6, font: "grotesk", r3: "#ff9a5a", r4: "#ff4d2e" }),
  P("Isotype", "After Neurath and Arntz: flat pictorial statistics, four inks, a bold person, no ornament. Readable in one glance.",
    { style: "3", lines: 2.2, cutLine: 2.6, cutStyle: "1", hInk: 1, hCut: 0.3, hPost: 4, hWash: 0.2, seam: 0, font: "grotesk",
      cPaper: "#efe8d8", cInk: "#1c1c1c", cCut: "#1c1c1c", cVeg: "#3f6e53", cAccent: "#c8341f",
      r0: "#2f5d8a", r1: "#8fa9b8", r2: "#d8ceb8", r3: "#e0764a", r4: "#c8341f", grain: 0.4, textScale: 1.1 }),
  P("Meteorological", "After Philippe Rahm's climatic drawings: soft temperature gradients like a weather map, thin grey lines, no hatching.",
    { style: "4", lines: 0.7, hWash: 0.6, hInk: 0.2, hCut: 1, cutStyle: "3", hIso: 0.35, hIsoStep: 1, vegAmt: 0.5, font: "grotesk", grain: 0.2,
      cutLine: 2.2, cPaper: "#f7f7f5", r0: "#3b7bd4", r1: "#9cc3e8", r2: "#eeeeea", r3: "#f7a35c", r4: "#e3413a", hTmin: -10, hTmax: 12 }),
  P("Weather radar", "A night-green screen, heat in radar colours.",
    { dark: true, cPaper: "#0d1a14", cInk: "#7fbf9a", cCut: "#9fd4b2", cVeg: "#2f7a4f", style: "1", hInk: 1, hCut: 1, cutStyle: "2",
      r0: "#1a3f33", r1: "#2f8f5b", r2: "#c9d64a", r3: "#f0a030", r4: "#ff3b30", hPost: 6, font: "mono", grain: 0.5, lines: 0.6 }),
  P("Pencil grid", "A quiet pencil grid over pale bands of heat, in the spirit of Agnes Martin.",
    { style: "8", spacing: 1.1, width: 0.8, hInk: 0.45, hWash: 0.22, hCut: 0.6, cutStyle: "2", lines: 0.5, vegAmt: 0.45, contrast: 0.6,
      cPaper: "#f5f1e8", r0: "#9fb6c9", r1: "#c9d3d6", r2: "#cfc7b8", r3: "#e2a88a", r4: "#d27060", font: "serif", grain: 1.4 }),
  P("Weave", "Warp and weft: every millimetre is a thread, its colour the temperature. After Anni Albers' Bauhaus weavings.",
    { style: "9", spacing: 0.9, hInk: 1, hCut: 1, cutStyle: "3", seam: 0, lines: 0.5, cPaper: "#efe6d4",
      r0: "#2f4b6e", r1: "#7c8e8a", r2: "#c8b89a", r3: "#d9823f", r4: "#a8322a", grain: 1.2 }),
  P("Instruction drawing", "In the spirit of Sol LeWitt's instructions: one direction of lines for mild heat, two for hot, three for very hot. Density IS temperature.",
    { toneHeat: 1, hInk: 0.25, style: "0", jitter: 0, t1: 0.52, t2: 0.7, t3: 0.86, spacing: 0.8, seam: 0, cutStyle: "3", hCut: 1,
      cPaper: "#fbfaf6", cInk: "#1d1d1b", lines: 0.6, vegAmt: 0.4, font: "grotesk", grain: 0.3 }),
  P("As found · photoreal", "The survey model itself, rendered in Blender (Cycles) at 22 Sep 17:40 with its real materials. The cut stays drawn; no heat overlay.",
    { style: "10", hInk: 0, hWash: 0, hCut: 0, cutStyle: "0", ovTemps: false, ovPerson: false, story: false, strip: false, ovLegend: false, depthFade: 0.3, lightFollows: false }),
  P("Photoreal + heat", "The real wall, and on top of it only the heat: a warm glaze where surfaces are hotter than the air, numbers and the person-thermometer.",
    { style: "10", hInk: 0, hWash: 0.35, hCut: 0.7, cutStyle: "0", depthFade: 0.3, lightFollows: false, hTmin: 0, hTmax: 14,
      r0: "#f3eee3", r1: "#f3eee3", r2: "#f1c8a0", r3: "#e0643a", r4: "#b8161a" }),
];
